### ISSUE TITLE
Evaluate/Implement Spring Boot Admin

### ISSUE THREAD

**Issue by fmendezh** [gbif/monitoring-service#1]
In the branch [spring-boot-admin](https://github.com/gbif/monitoring-service/commits/spring-boot-admin) there's a proposal to use 
[https://github.com/codecentric/spring-boot-admin](https://github.com/codecentric/spring-boot-admin) to monitor the running Spring applications, to use this monitoring app the service all ws applications must be changed to be able to communicate with the admin server.

The goal of this task is to evaluate and/or develop and deploy the admin monitoring application  (if that is the decision made).

**Comment by marcos-lg** [comment]
It will be continued in this project https://github.com/gbif/spring-monitoring because in the current one there are conflicts with the zookeeper and curator dependencies and it's causing problems to make the Spring Boot Admin discover all the WSs in ZK.

**Comment by marcos-lg** [comment]
A preliminary version has been deployed at http://ws.gbif-dev.org:10004/
